#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: WindyCityCoffee
# Website language
lang: en-US
# Header Title
header-title: for <strong>Healthy</strong> Coffee
# Header Tagline
headter-tagline: Forging the way

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Learn More
  url: '#about'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: "jimmy@windycitycoffee.com"

# Offer Banner Link
# Default link is a link to all Sera OnePage products

####################################
######  Global Social Links   ######
####################################
linkedIn: "#"
instagram: "#"

#########################
######   Widgets   ######
#########################


# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Windy City Coffee
map-text-location: Chicago, Illinois
map-lat: 41.903861
map-lng: -87.677466

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome to Windy City Coffee
about-description: Based in the heart of Chicago, we're a startup focused on bringing healthy coffee products to customers across the world. With years of experience establishing relationships with coffee farmers, roasters, and manufacturers, we have perfected the supply chain management of building successful coffee brands.


#####################################
#############  Features  ############
#####################################
features-title: Our Partners
features-description: We have partnered with some of the best resources in the coffee industry. 

#
# Features
#
features:

# Feature
- title: HealthWise Coffee
  description: The original Low-Acid Coffee. A family owned company based out of the Chicago suburbs, HealthWise has paved the way for WindyCity Coffee's success.
  # icon: pe-7s-vector
  icon: pe-7s-healthwise

# Feature
- title: Brim Coffee
  description: A classic! Brim coffee was the number 1 coffee in the 60s, announcing it's comeback, WindyCity Coffee has partnered with Brim to reinvigorate this timeless brand.
  icon: pe-7s-brim

# Feature
- title: TechnoRoasting™
  description: The <i>Secret Formula</i> for our coffee. The sole reason we can produce such high quality coffee with so many health benefits.
  icon: pe-7s-technoroasting


#####################################
##########  Core Features  ##########
#####################################
core-title: What makes us different
core-description: Powered by TechnoRoasting™, our brands have the lowest acid, and the highest vitamin and mineral count compared to any coffee on the market. The FDA approved process results in an all-natural, nutrient boosted cup of delicious coffees. 

#
# Core Features Left
#
core-features-left:

# Feature
- name: Vitamin Rich
  description: The highest vitamins and minerals in any coffee.
  icon: pe-7s-coffee

# Feature
- name: All Natural
  description: The FDA approved roasting process results in a purely unadulterated coffee. 
  icon: pe-7s-leaf

# # Feature
# - name: Clean Coding
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-coffee

# # Feature
# - name: Friendly
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-smile

#
# Core Features Right
#
core-features-right:

# Feature
- name: High Quality
  description: We source only the finest Arabica coffee beans from Colombia.
  icon: pe-7s-global

# Feature
- name: Award Winning
  description: We have been rated the number 1 Low Acid Swiss Water decaf in the U.S.
  icon: pe-7s-medal

# # Feature
# - name: Graphic Design
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-crop

# # Feature
# - name: Photography
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-camera


#####################################
########### Solutions ############
#####################################

solutions-title: Our Solutions
solutions-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# solutions Features Left
#
solutions-features:

# Feature
- name: Distribution
  description: We specialize in distributing and managing your coffee brand. Everything from E-commerce, and order fufillment. Ensuring your product grows from conception and on the shelves.
  icon: pe-7s-refresh

# Feature
- name: Roasting
  description: The possibilities are endless for coffee choices. We can provide a multitude of cost effective and delicious roasts of coffees grown all across the globe.
  icon: pe-7s-coffee

# Feature
- name: Organic, Fair-Trade Coffees
  description: We can produce the highest quality coffees available. Our specialty brand, HealthWise, is one of the highest quality coffees available, truley 100% Arabic Colombian Supremo.
  icon: pe-7s-leaf

# Feature
- name: Private Labeling
  description: We help you every step of the way in development of your coffee brand. You provide the idea, we provide the coffee.
  icon: pe-7s-star

#####################################
############### Team ################
#####################################
team-title: Who We Are
team-description: With years of experience growing HealthWise, we have branched off into WindyCity Coffee with a goal of expanding our line of coffee products. Our goal is to bring the power of TechnoRoasting™ to the shelves of consumers. 

#
# Team Members
#
team:

# Team Member
- name: Jimmy Couch
  tagline: Founder
  avatar: jimmy-puppy.jpg
  # avatar: jimmy.png

  # Social Links
  linkedIn: 'https://www.linkedin.com/in/jimmy-couch-15aaa954/'
  instagram: "https://www.instagram.com/healthwisegourmetcoffees/"


#####################################
############   Contact   ############
#####################################
contact-title: Want to learn more?
contact-description: We'll be happy to help answer any questions you may have on our products, and the services we provide. 


#####################################
#############   Footer   ############
#####################################
footer-description: Made with ❤️ in Chicago
footer-copyright-text: WindyCityCoffee
footer-copyright-url: http://www.windycitycoffee.com
footer-copyright-year: 2017
